feat: UserInfo answers & comments 조회 기능 구현
codestates-seb/seb39_main_049 pull request #119
Opened 2022-09-24 00:48 UTC by yeonkkk

### Summary
UserInfo answers & comments 조회 기능 구현하였습니다.

### Key Changes 
- 유저 페이지 조회 시 사용할 answers 구현
- 유저 페이지 조회 시 사용할 comments 구현

### To Reviewers
`super.doFilterInternal(request, response, chain);` 코드를 주석처리하지 않으면 반환이 2번 됩니다.. 
다른 조회 메서드랑 비교하면 토큰 필요 유무 차이가 있는 것 같습니다.
유저페이지 조회같은 경우는 로그인이 필요하지 않은 서비스이기 때문에 제외해도 좋을 것 같습니다.
그런데 이전에 이 코드를 주석처리하고 안하고의 차이를 궁금해하셨던 것 같아서 이번 기회에 확인해보시면 좋을 것 같아요!

### Issue number
#116

2022-09-24 00:50 UTC, yeonkkk commented
인후님은 상황 공유를 위해 리뷰어로 추가하였습니다.

2022-09-24 06:16 UTC, klkim1913 commented on server/src/main/java/server/answer/dto/AnswerUserResponseDto.java
> +    private String subCategory;
main카테고리는 따로 안들어간 이유가 있을까요?

2022-09-24 06:17 UTC, klkim1913 commented on server/src/main/java/server/comment/dto/CommentUserResponseDto.java
> +    private String subCategory;
AnswerUserResponseDto와 동일.

2022-09-24 06:21 UTC, klkim1913 requested changes

2022-09-24 06:21 UTC, klkim1913 commented on server/src/main/java/server/user/service/UserService.java
>          return user.orElseThrow(Exception::new);
비즈니스 로직으로 에러처리 통일하면 좋을것같습니다!

2022-09-24 13:52 UTC, yeonkkk commented on server/src/main/java/server/answer/dto/AnswerUserResponseDto.java
> +    private String subCategory;
인후님께서 저 요소들만 요청하셔서 일단 요청하신 대로 구현했습니다! (노션 회의록 참조)

2022-09-24 13:53 UTC, yeonkkk commented on server/src/main/java/server/comment/dto/CommentUserResponseDto.java
> +    private String subCategory;
저도 통합해서 구현할까 하다가 api 를 구분해서 요청하게 해달라고 하셔서 일단 따로 구현했습니다. 
수정하는게 나을 것 같으면 변경해도 괜찮을 것 같아요!

2022-09-25 06:13 UTC, klkim1913 approved these changes

2022-09-25 06:13 UTC, klkim1913 commented on server/src/main/java/server/comment/dto/CommentUserResponseDto.java
> +    private String subCategory;
통합 구현이 아니라 위와 같은 커멘트라는 뜻이였어요..!

2022-09-25 06:14 UTC, merged